import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { Store } from '../utils/Store'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import { signOut, useSession } from 'next-auth/react';
import { Menu } from '@headlessui/react';
import DropdownLink from './DropdownLink'
import Cookies from 'js-cookie'

export default function Layout({children, title}) {
    const {status, data: session} = useSession();
    const {state, dispatch} = useContext(Store);
    const {cart} = state;
    const [cartItemsCount, setCartItemsCount] = useState(0);

    useEffect(() => {
        setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0))
    },[cart.cartItems]);

    const logoutClickHandler = () => {
        Cookies.remove('cart');
        dispatch({ type: 'CART_RESET' });
        signOut({ callbackUrl: '/login' });
    }
  return (
    <>
        <Head>
            <title>{title? `${title} - Dosimple`:'Dosimple'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <ToastContainer position='top-center' limit={1}></ToastContainer>
    <div className="flex min-h-screen flex-col justify-between">
        <header className='sticky top-0 z-10 bg-white'>
            <nav className='flex h-12 justify-between shadow-md items-center px-4'>
                <Link href='/'>
                    <a className='text-lg font-bold'>Dosimple</a>
                </Link>
                <div>
                    <Link href='/cart'>
                    <a className='p-4'>Cart
                        {cartItemsCount > 0 && (
                        <span className='ml-1 rounded-full text-xs font-bold bg-indigo-700 text-white px-2 py-1'>
                            {cartItemsCount}
                        </span>
                        )}
                    </a>
                    </Link>
                        { status === 'loading' ? ('Loading')
                        : session?.user ? (<Menu as="div" className='relative inline-block'>
                                                <Menu.Button className='text-indigo-700 font-bold'>{session.user.name}</Menu.Button>
                                                <Menu.Items className="absolute right-0 w-44 original-top-right bg-white shadow-lg">
                                                    <Menu.Item>
                                                        <DropdownLink className="dropdown-link" href="/profile">Profile</DropdownLink>
                                                    </Menu.Item>
                                                    <Menu.Item>
                                                        <DropdownLink className="dropdown-link" href="/order-history">Order History</DropdownLink>
                                                    </Menu.Item>
                                                    <Menu.Item>
                                                        <a className="dropdown-link" href="#" onClick={logoutClickHandler}>Logout</a>
                                                    </Menu.Item>
                                                </Menu.Items>
                                          </Menu>)
                        : ( <Link href='/login'><a className='p-2'>Login</a></Link>)
                        }
                </div>
            </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>{children}</main>
        <footer className='flex h-10 justify-center items-center shadow-inner'>Copyright &copy; 2022 Dosimple</footer>
    </div>
    </>
  )
}
